//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace PanGu
{
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class AnalyzerResource
    {

        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyzerResource()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("PanGu.Properties.AnalyzerResource", typeof(AnalyzerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 beat	beat	beaten
        ///become	became	become
        ///begin	began	begun
        ///bend	bent	bent
        ///bet	bet	bet
        ///bid	bid	bid
        ///bite	bit	bitten
        ///bleed	bled	bled
        ///blow	blew	blown
        ///break	broke	broken
        ///breed	bred	bred
        ///bring	brought	brought
        ///broadcast	broadcast	broadcast
        ///build	built	built
        ///buy	bought	bought
        ///catch	caught	caught
        ///choose	chose	chosen
        ///cling	clung	clung
        ///come	came	come
        ///cost	cost	cost
        ///creep	crept	crept
        ///cut	cut	cut
        ///deal	dealt	dealt
        ///dig	dug	dug
        ///do	did	done
        ///draw	drew	drawn
        ///dream	dreamed	dreamt
        ///drink	drank	drunk
        ///driv [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string INFINITIVE
        {
            get
            {
                return ResourceManager.GetString("INFINITIVE", resourceCulture);
            }
        }
    }
}
